# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [79]:
#pip install py gmaps

In [5]:
# Dependencies and Setup
%matplotlib notebook

import gmaps
import pandas as pd
import gmaps.datasets
import csv
import numpy as np
import requests
import time
from scipy.stats import linregress
import matplotlib.pyplot as plt
from scipy import stats
import ipywidgets as widgets
import logging
logging.basicConfig(level=logging.DEBUG)
# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy



# Google developer API key
from api_keys_6 import g_key




#weather_data_short_load= "weather_data_short.csv"
#wds_df = pd.read_csv(weather_data_short_load)

DEBUG:matplotlib.pyplot:Loaded backend nbAgg version unknown.

In [3]:
weather_data_to_load= "weather_data.csv"
weather_data = pd.read_csv(weather_data_to_load)
#pip install py gmaps

In [4]:
weather_data

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
0,Lebu,CL,-37.6167,-73.6500,17.99,17.99,1,73,4.52,1614967499
1,Jamestown,US,42.0970,-79.2353,-3.10,-2.78,90,91,8.32,1614967499
2,Barrow,US,71.2906,-156.7887,-23.00,-23.00,90,64,9.77,1614967500
3,Dunedin,NZ,-45.8742,170.5036,9.96,9.96,97,81,2.14,1614967500
4,Tasiilaq,GL,65.6145,-37.6368,4.00,4.00,75,81,5.66,1614968031
...,...,...,...,...,...,...,...,...,...,...
547,Muroto-misakicho,JP,33.2833,134.1500,16.31,16.31,92,78,5.48,1614968344
548,Tabas,IR,33.5959,56.9244,20.02,20.02,32,44,8.04,1614968345
549,Boa Vista,BR,2.8197,-60.6733,32.00,32.00,75,45,7.20,1614968345
550,Roura,GF,4.7263,-52.3274,26.55,27.22,90,83,3.60,1614968345
551,Imbituba,BR,-28.2400,-48.6703,27.00,27.00,75,78,5.14,1614968347

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
weather_data.head()

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
0,Lebu,CL,-37.6167,-73.6500,17.99,17.99,1,73,4.52,1614967499
1,Jamestown,US,42.0970,-79.2353,-3.10,-2.78,90,91,8.32,1614967499
2,Barrow,US,71.2906,-156.7887,-23.00,-23.00,90,64,9.77,1614967500
3,Dunedin,NZ,-45.8742,170.5036,9.96,9.96,97,81,2.14,1614967500
4,Tasiilaq,GL,65.6145,-37.6368,4.00,4.00,75,81,5.66,1614968031

In [3]:
#This smaller data set is to be used for debugging and trial

28

In [10]:
vfd= weather_data.head()

In [11]:
vfd

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
0,Lebu,CL,-37.6167,-73.6500,17.99,17.99,1,73,4.52,1614967499
1,Jamestown,US,42.0970,-79.2353,-3.10,-2.78,90,91,8.32,1614967499
2,Barrow,US,71.2906,-156.7887,-23.00,-23.00,90,64,9.77,1614967500
3,Dunedin,NZ,-45.8742,170.5036,9.96,9.96,97,81,2.14,1614967500
4,Tasiilaq,GL,65.6145,-37.6368,4.00,4.00,75,81,5.66,1614968031

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [22]:
#Configure gmaps
import gmaps
gmaps.configure(api_key=g_key)

In [23]:
#plocations = vfd[["lat", "lon"]].astype(float)

#prating = vfd["humidity"]

In [25]:
 # Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=5)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
vacay_data= weather_data
vacay_data

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
0,Lebu,CL,-37.6167,-73.6500,17.99,17.99,1,73,4.52,1614967499
1,Jamestown,US,42.0970,-79.2353,-3.10,-2.78,90,91,8.32,1614967499
2,Barrow,US,71.2906,-156.7887,-23.00,-23.00,90,64,9.77,1614967500
3,Dunedin,NZ,-45.8742,170.5036,9.96,9.96,97,81,2.14,1614967500
4,Tasiilaq,GL,65.6145,-37.6368,4.00,4.00,75,81,5.66,1614968031
...,...,...,...,...,...,...,...,...,...,...
547,Muroto-misakicho,JP,33.2833,134.1500,16.31,16.31,92,78,5.48,1614968344
548,Tabas,IR,33.5959,56.9244,20.02,20.02,32,44,8.04,1614968345
549,Boa Vista,BR,2.8197,-60.6733,32.00,32.00,75,45,7.20,1614968345
550,Roura,GF,4.7263,-52.3274,26.55,27.22,90,83,3.60,1614968345
551,Imbituba,BR,-28.2400,-48.6703,27.00,27.00,75,78,5.14,1614968347

In [26]:
locations = vacay_data[["lat", "lon"]].astype(float)

rating = vacay_data["humidity"]


 # Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=4)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
#vac_lon_coords=vfd['lon'].tolist()
#vac_lon_coords
#vac_lat_coords=vfd['lat'].tolist()
#vac_lat_coords

In [ ]:
locations = vacay_data[["lat", "lon"]].astype(float)

rating = vacay_data["humidity"]


 # Plot Heatmap
fig = gmaps.figure(map_type='HYBRID')

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)
# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [28]:
vacay_filter_df=weather_data.loc[(weather_data["temp_max"]<30) & (weather_data["temp_max"]>19)& (weather_data["cloudiness"]==0)& (weather_data["windspeed"]<10)]
len(vacay_filter_df)

39

In [29]:
vacay_filter_df.to_csv('perfect_vacation_filtered_data.csv', index=False, header=True)

In [30]:
vacay_filter_df

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082
118,Mongo,TD,12.1844,18.6930,29.50,29.50,0,13,3.54,1614968083
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091
162,Adrar,MR,20.5022,-10.0711,29.23,29.23,0,12,1.87,1614968101
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112
204,Bitkine,TD,11.9801,18.2138,29.38,29.38,0,13,3.64,1614968158
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114
292,Soyung,PH,16.7001,121.6655,20.68,20.68,0,92,0.52,1614968197
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201
314,Bilma,NE,18.6853,12.9164,25.24,25.24,0,15,4.02,1614968207
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303
479,Sakīt,IN,27.4500,78.8167,21.04,21.04,0,22,4.47,1614968316
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325
514,Najrān,SA,17.4924,44.1277,25.00,25.00,0,25,6.17,1614968331

In [31]:
#remove highest humidty locations for a more pleasurable vacation
#perfect_vacation_df=weather_data.loc[(weather_data["temp_max"]<30) & (weather_data["temp_max"]>20)& (weather_data["cloudiness"]==0)& (weather_data["windspeed"]<10)& (weather_data["humidity"]<70)]
#len(perfect_vacation_df)

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [32]:
#NaN = np.nan
#df["column3"] = NaN
#pv_df['new_column']
#pv_df['colum11']
hotel_df= vacay_filter_df

In [17]:
# Google developer API key
from config import g_key

###Hotel Map

#Store into variable named hotel_df
hotel_df= locations = pv_df[["lat", "lon"]].astype(float)

rating = pv_df["humidity"]
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=2)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

In [19]:
#pv_df2=pv_df

In [20]:
#pv_df2["Hotel Name"]=""
#pv_df2

<ipython-input-20-b18d459c3b2e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pv_df2["Hotel Name"]=""

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
110,Ancud,CL,-41.8697,-73.8203,20.13,21.00,0,49,2.57,1613158839,
125,Beïnamar,TD,8.6698,15.3813,25.04,25.04,0,17,1.59,1613158934,
181,Sur,OM,22.5667,59.5289,20.64,20.64,0,63,3.33,1613158948,
183,Río Gallegos,AR,-51.6226,-69.2181,24.00,24.00,0,20,4.63,1613158949,
214,Camaná,PE,-16.6228,-72.7111,24.88,24.88,0,63,3.73,1613159033,
294,Adré,TD,13.4667,22.2000,21.77,21.77,0,21,3.55,1613159052,
300,Makkah al Mukarramah,SA,21.4267,39.8261,25.00,25.00,0,57,1.43,1613158921,
335,Salalah,OM,17.0151,54.0924,23.00,23.00,0,49,1.54,1613158852,
364,Pitrufquén,CL,-38.9833,-72.6500,26.00,26.00,0,57,5.14,1613159071,
370,Atar,MR,20.5169,-13.0499,22.28,22.28,0,17,4.77,1613159073,
380,Adrar,MR,20.5022,-10.0711,22.36,22.36,0,16,5.02,1613159151,
413,Tessalit,ML,20.1986,1.0114,22.26,22.26,0,16,2.29,1613159162,
442,Keti Bandar,PK,24.1447,67.4497,20.56,20.56,0,67,3.96,1613159169,
446,Coyhaique,CL,-45.5752,-72.0662,24.00,24.00,0,29,3.09,1613159127,
470,Ormara,PK,25.2088,64.6357,21.11,21.11,0,64,3.25,1613159175,
500,Bokoro,TD,12.3807,17.0568,25.46,25.46,0,16,3.19,1613159184,
524,Umluj,SA,25.0213,37.2685,24.86,24.86,0,60,1.85,1613159189,
561,Illapel,CL,-31.6308,-71.1653,26.70,26.70,0,40,4.42,1613159198,

In [33]:
hotel_df

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082
118,Mongo,TD,12.1844,18.6930,29.50,29.50,0,13,3.54,1614968083
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091
162,Adrar,MR,20.5022,-10.0711,29.23,29.23,0,12,1.87,1614968101
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112
204,Bitkine,TD,11.9801,18.2138,29.38,29.38,0,13,3.64,1614968158
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114
292,Soyung,PH,16.7001,121.6655,20.68,20.68,0,92,0.52,1614968197
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201
314,Bilma,NE,18.6853,12.9164,25.24,25.24,0,15,4.02,1614968207
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303
479,Sakīt,IN,27.4500,78.8167,21.04,21.04,0,22,4.47,1614968316
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325
514,Najrān,SA,17.4924,44.1277,25.00,25.00,0,25,6.17,1614968331

In [34]:
#hotel_df
#Add a "Hotel Name" column to the DataFrame.
#>>> df["C"] = ""
hotel_df["Hotel Name"]=""
hotel_df

<ipython-input-34-d3be8de8d194>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"]=""

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,
118,Mongo,TD,12.1844,18.6930,29.50,29.50,0,13,3.54,1614968083,
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,
162,Adrar,MR,20.5022,-10.0711,29.23,29.23,0,12,1.87,1614968101,
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,
204,Bitkine,TD,11.9801,18.2138,29.38,29.38,0,13,3.64,1614968158,
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,
292,Soyung,PH,16.7001,121.6655,20.68,20.68,0,92,0.52,1614968197,
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,
314,Bilma,NE,18.6853,12.9164,25.24,25.24,0,15,4.02,1614968207,
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,
479,Sakīt,IN,27.4500,78.8167,21.04,21.04,0,22,4.47,1614968316,
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,
514,Najrān,SA,17.4924,44.1277,25.00,25.00,0,25,6.17,1614968331,

In [35]:
# Google developer API key
#from config import g_key

In [37]:
params = {
    "radius": 5000,
    "types": "Hotel",
    "keyword": "Hotel",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lats = row["lat"]
    lons = row["lon"]    
    # change location each iteration while leaving original params in place
    params["location"] = f"{lats},{lons}"    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    
    # make request and print url
    name_address = requests.get(base_url, params=params)
    #print the name_address url, avoid doing for public github repos in order to avoid exposing key
    print(name_address.url)  
    # convert to json
    name_address = name_address.json()
    #print(json.dumps(name_address, indent=4, sort_keys=True))    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443
DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.9258%2C18.4232 HTTP/1.1" 200 6850
/Users/crloud/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.9258%2C18.4232

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-24.8667%2C113.6333 HTTP/1.1" 200 4433
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-24.8667%2C113.6333

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=25.0213%2C37.2685 HTTP/1.1" 200 1915
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=25.0213%2C37.2685

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-41.8697%2C-73.8203 HTTP/1.1" 200 6416
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-41.8697%2C-73.8203

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-34.4187%2C19.2345 HTTP/1.1" 200 6679
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-34.4187%2C19.2345

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.0153%2C27.9116 HTTP/1.1" 200 6749
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.0153%2C27.9116

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=10.0167%2C105.0833 HTTP/1.1" 200 7146
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=10.0167%2C105.0833

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.0117%2C17.9442 HTTP/1.1" 200 2095
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-33.0117%2C17.9442

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=26.1615%2C32.7183 HTTP/1.1" 200 1883
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=26.1615%2C32.7183

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=27.9769%2C-114.0611 HTTP/1.1" 200 4782
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=27.9769%2C-114.0611

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=12.1844%2C18.692999999999998 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=12.1844%2C18.692999999999998
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.930999999999997%2C-17.0347 HTTP/1.1" 200 4731
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.930999999999997%2C-17.0347

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.6453%2C70.6567 HTTP/1.1" 200 5312
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.6453%2C70.6567

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.5022%2C-10.0711 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.5022%2C-10.0711
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-12.1167%2C-77.05 HTTP/1.1" 200 6934
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-12.1167%2C-77.05

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-22.116%2C14.2845 HTTP/1.1" 200 3336
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-22.116%2C14.2845

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-34.5322%2C20.0403 HTTP/1.1" 200 3705
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-34.5322%2C20.0403

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=11.9801%2C18.2138 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=11.9801%2C18.2138
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=10.9333%2C108.1 HTTP/1.1" 200 6881
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=10.9333%2C108.1

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-31.6683%2C18.5012 HTTP/1.1" 200 3201
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-31.6683%2C18.5012

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.9%2C70.3667 HTTP/1.1" 200 6870
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.9%2C70.3667

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=16.4833%2C81.8333 HTTP/1.1" 200 3171
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=16.4833%2C81.8333

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=11.6667%2C92.75 HTTP/1.1" 200 6758
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=11.6667%2C92.75

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=16.7001%2C121.6655 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=16.7001%2C121.6655
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=19.8%2C75.5333 HTTP/1.1" 200 857
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=19.8%2C75.5333

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=18.6853%2C12.9164 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=18.6853%2C12.9164
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-26.6481%2C15.1594 HTTP/1.1" 200 6512
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-26.6481%2C15.1594

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.1833%2C76.6167 HTTP/1.1" 200 2918
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.1833%2C76.6167

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-45.5752%2C-72.0662 HTTP/1.1" 200 6776
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-45.5752%2C-72.0662

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=17.0151%2C54.0924 HTTP/1.1" 200 6202
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=17.0151%2C54.0924

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-17.2614%2C27.4618 HTTP/1.1" 200 1375
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-17.2614%2C27.4618

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=19.1059%2C37.3321 HTTP/1.1" 200 1104
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=19.1059%2C37.3321

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-13.7%2C-76.2167 HTTP/1.1" 200 2308
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-13.7%2C-76.2167

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-29.038%2C24.6028 HTTP/1.1" 200 816
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=-29.038%2C24.6028

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.8947%2C64.4101 HTTP/1.1" 200 2133
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=28.8947%2C64.4101

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=18.4167%2C84.05 HTTP/1.1" 200 992
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=18.4167%2C84.05

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=27.45%2C78.8167 HTTP/1.1" 200 83
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=27.45%2C78.8167
Missing field/result... skipping.

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.635%2C82.0614 HTTP/1.1" 200 2274
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): maps.googleapis.com:443

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=20.635%2C82.0614

DEBUG:urllib3.connectionpool:https://maps.googleapis.com:443 "GET /maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=17.4924%2C44.1277 HTTP/1.1" 200 83

https://maps.googleapis.com/maps/api/place/nearbysearch/json?radius=5000&types=Hotel&keyword=Hotel&key=AIzaSyBY7hoCeoa6tnTT8n-kaD-C-JhJmsS5bHo&location=17.4924%2C44.1277
Missing field/result... skipping.

In [38]:
hotel_df

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal
118,Mongo,TD,12.1844,18.6930,29.50,29.50,0,13,3.54,1614968083,
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel
162,Adrar,MR,20.5022,-10.0711,29.23,29.23,0,12,1.87,1614968101,
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage
204,Bitkine,TD,11.9801,18.2138,29.38,29.38,0,13,3.64,1614968158,
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis
292,Soyung,PH,16.7001,121.6655,20.68,20.68,0,92,0.52,1614968197,
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar
314,Bilma,NE,18.6853,12.9164,25.24,25.24,0,15,4.02,1614968207,
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel
479,Sakīt,IN,27.4500,78.8167,21.04,21.04,0,22,4.47,1614968316,
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY
514,Najrān,SA,17.4924,44.1277,25.00,25.00,0,25,6.17,1614968331,

In [43]:
hotel_df

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal
118,Mongo,TD,12.1844,18.6930,29.50,29.50,0,13,3.54,1614968083,
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel
162,Adrar,MR,20.5022,-10.0711,29.23,29.23,0,12,1.87,1614968101,
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage
204,Bitkine,TD,11.9801,18.2138,29.38,29.38,0,13,3.64,1614968158,
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis
292,Soyung,PH,16.7001,121.6655,20.68,20.68,0,92,0.52,1614968197,
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar
314,Bilma,NE,18.6853,12.9164,25.24,25.24,0,15,4.02,1614968207,
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel
479,Sakīt,IN,27.4500,78.8167,21.04,21.04,0,22,4.47,1614968316,
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY
514,Najrān,SA,17.4924,44.1277,25.00,25.00,0,25,6.17,1614968331,

In [44]:
hotel_df_clean=hotel_df.drop([118,162,204,292,314,479,514])

In [45]:
hotel_df_clean

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
29,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel
55,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments
60,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel
63,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud
80,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven
85,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel
98,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel
112,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel
113,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees
116,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal
130,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA
137,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel
169,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima
183,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose
184,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage
209,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel
246,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage
250,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM
266,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari
272,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis
300,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar
341,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL
346,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace
349,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia
361,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel
377,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge
391,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل
403,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente
405,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel
429,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant
449,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel
499,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY

In [46]:

hotel_df_clean.reset_index(drop=True, inplace=True)

In [47]:
hotel_df_clean

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
0,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel
1,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments
2,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel
3,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud
4,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven
5,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel
6,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel
7,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel
8,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees
9,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal
10,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA
11,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel
12,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima
13,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose
14,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage
15,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel
16,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage
17,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM
18,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari
19,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis
20,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar
21,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL
22,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace
23,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia
24,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel
25,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge
26,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل
27,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente
28,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel
29,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant
30,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel
31,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY

In [61]:
hotel_df_clean.to_csv('hotel_data.csv', index = False)

In [63]:
hd=hotel_df_clean
hd

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name,hotel info
0,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel,\n<dl>\n<dt>Name</dt><dd>Atlanticview Cape Tow...
1,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments,\n<dl>\n<dt>Name</dt><dd>Carnarvon Sea Change ...
2,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel,\n<dl>\n<dt>Name</dt><dd>HP Red Sea Hotel</dd>...
3,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud,\n<dl>\n<dt>Name</dt><dd>Panamericana Hotel An...
4,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven,\n<dl>\n<dt>Name</dt><dd>Ocean Eleven</dd>\n<d...
5,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel,\n<dl>\n<dt>Name</dt><dd>Blue Lagoon Hotel</dd...
6,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel,\n<dl>\n<dt>Name</dt><dd>Sai Gon Rach Gia Hote...
7,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel,\n<dl>\n<dt>Name</dt><dd>Hoedjiesbaai Hotel</d...
8,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees,\n<dl>\n<dt>Name</dt><dd>Movenpick MS Hamees</...
9,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal,\n<dl>\n<dt>Name</dt><dd>Hotel TerraSal</dd>\n...
10,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA,\n<dl>\n<dt>Name</dt><dd>HOTEL VALENCIA</dd>\n...
11,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel,\n<dl>\n<dt>Name</dt><dd>Marhaba Guest House a...
12,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima,\n<dl>\n<dt>Name</dt><dd>Selina Miraflores Lim...
13,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose,\n<dl>\n<dt>Name</dt><dd>Desert Rose</dd>\n<dt...
14,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage,\n<dl>\n<dt>Name</dt><dd>Rooftops Guest Cottag...
15,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel,\n<dl>\n<dt>Name</dt><dd>P'House Hotel</dd>\n<...
16,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage,\n<dl>\n<dt>Name</dt><dd>Voni's Cottage</dd>\n...
17,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM,\n<dl>\n<dt>Name</dt><dd>HOTEL PLATINUM</dd>\n...
18,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari,\n<dl>\n<dt>Name</dt><dd>Dindi By The Godavari...
19,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis,\n<dl>\n<dt>Name</dt><dd>Hotel Reef Atlantis</...
20,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar,\n<dl>\n<dt>Name</dt><dd>Hotel Siddheshwar</dd...
21,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL,\n<dl>\n<dt>Name</dt><dd>LÜDERITZ NEST HOTEL</...
22,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace,\n<dl>\n<dt>Name</dt><dd>Hotel Deep Palace</dd...
23,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia,\n<dl>\n<dt>Name</dt><dd>Hotel Dreams de la Pa...
24,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel,\n<dl>\n<dt>Name</dt><dd>Salalah Gardens Hotel...
25,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge,\n<dl>\n<dt>Name</dt><dd>Lakeview Lodge</dd>\n...
26,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل,\n<dl>\n<dt>Name</dt><dd>Arab Plaza Hotel عرب ...
27,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente,\n<dl>\n<dt>Name</dt><dd>Hotel Presidente</dd>...
28,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel,\n<dl>\n<dt>Name</dt><dd>The Cygnature Boutiqu...
29,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant,\n<dl>\n<dt>Name</dt><dd>Al-Dawood Hotel & Res...
30,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel,\n<dl>\n<dt>Name</dt><dd>SPR Grand Hotel</dd>\...
31,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY,\n<dl>\n<dt>Name</dt><dd>HOTEL CITY REGENCY</d...

In [66]:
hd.drop(columns=['hotel info'])

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name
0,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel
1,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments
2,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel
3,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud
4,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven
5,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel
6,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel
7,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel
8,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees
9,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal
10,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA
11,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel
12,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima
13,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose
14,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage
15,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel
16,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage
17,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM
18,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari
19,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis
20,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar
21,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL
22,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace
23,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia
24,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel
25,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge
26,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل
27,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente
28,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel
29,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant
30,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel
31,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY

In [50]:
 # NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{citylist}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hd.iterrows()]
locations = hd[["lat", "lon"]]

In [51]:
markers = gmaps.marker_layer(locations)
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
)
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig
#Perfect Vacation Destination Map for those looking for light wind, cloudless skies, and warm weather.

Figure(layout=FigureLayout(height='420px'))

In [67]:
 
    # NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{citylist}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hd.iterrows()]
locations = hd[["lat", "lon"]]

In [68]:
markers = gmaps.marker_layer(locations)
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
    
)
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig
#Perfect Vacation Destination Map for those looking for light wind, cloudless skies, and warm weather.

Figure(layout=FigureLayout(height='420px'))

In [70]:
locations = hd[["lat", "lon"]].astype(float)

rating = hd["humidity"]


 # Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=4)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [78]:
hd['hotel info']= hotel_info
hd

,citylist,country,lat,lon,temp,temp_max,cloudiness,humidity,windspeed,date,Hotel Name,hotel info
0,Cape Town,ZA,-33.9258,18.4232,20.60,22.78,0,77,7.20,1614967842,Atlanticview Cape Town Boutique Hotel,\n<dl>\n<dt>Name</dt><dd>Atlanticview Cape Tow...
1,Carnarvon,AU,-24.8667,113.6333,24.00,24.00,0,94,6.17,1614967877,Carnarvon Sea Change Apartments,\n<dl>\n<dt>Name</dt><dd>Carnarvon Sea Change ...
2,Umluj,SA,25.0213,37.2685,22.44,22.44,0,39,9.25,1614968055,HP Red Sea Hotel,\n<dl>\n<dt>Name</dt><dd>HP Red Sea Hotel</dd>...
3,Ancud,CL,-41.8697,-73.8203,24.21,25.00,0,31,3.09,1614968057,Panamericana Hotel Ancud,\n<dl>\n<dt>Name</dt><dd>Panamericana Hotel An...
4,Hermanus,ZA,-34.4187,19.2345,21.11,21.11,0,74,2.68,1614968066,Ocean Eleven,\n<dl>\n<dt>Name</dt><dd>Ocean Eleven</dd>\n<d...
5,East London,ZA,-33.0153,27.9116,20.00,20.00,0,83,2.06,1614968068,Blue Lagoon Hotel,\n<dl>\n<dt>Name</dt><dd>Blue Lagoon Hotel</dd...
6,Rach Gia,VN,10.0167,105.0833,24.00,24.00,0,100,2.53,1614968073,Sai Gon Rach Gia Hotel,\n<dl>\n<dt>Name</dt><dd>Sai Gon Rach Gia Hote...
7,Saldanha,ZA,-33.0117,17.9442,23.00,23.00,0,46,2.06,1614968080,Hoedjiesbaai Hotel,\n<dl>\n<dt>Name</dt><dd>Hoedjiesbaai Hotel</d...
8,Qena,EG,26.1615,32.7183,21.00,21.00,0,30,1.03,1614968080,Movenpick MS Hamees,\n<dl>\n<dt>Name</dt><dd>Movenpick MS Hamees</...
9,Guerrero Negro,MX,27.9769,-114.0611,21.19,21.19,0,28,2.55,1614968082,Hotel TerraSal,\n<dl>\n<dt>Name</dt><dd>Hotel TerraSal</dd>\n...
10,Nouadhibou,MR,20.9310,-17.0347,21.00,21.00,0,64,9.77,1614968088,HOTEL VALENCIA,\n<dl>\n<dt>Name</dt><dd>HOTEL VALENCIA</dd>\n...
11,Khanpur,PK,28.6453,70.6567,21.01,21.01,0,22,1.89,1614968091,Marhaba Guest House and Hotel,\n<dl>\n<dt>Name</dt><dd>Marhaba Guest House a...
12,San Isidro,PE,-12.1167,-77.0500,27.00,27.00,0,61,6.17,1614968104,Selina Miraflores Lima,\n<dl>\n<dt>Name</dt><dd>Selina Miraflores Lim...
13,Henties Bay,NaN,-22.1160,14.2845,22.20,22.20,0,59,4.94,1614968109,Desert Rose,\n<dl>\n<dt>Name</dt><dd>Desert Rose</dd>\n<dt...
14,Bredasdorp,ZA,-34.5322,20.0403,20.00,20.00,0,83,4.12,1614968112,Rooftops Guest Cottage,\n<dl>\n<dt>Name</dt><dd>Rooftops Guest Cottag...
15,Phan Thiet,VN,10.9333,108.1000,21.47,21.47,0,83,3.37,1614968160,P'House Hotel,\n<dl>\n<dt>Name</dt><dd>P'House Hotel</dd>\n<...
16,Vredendal,ZA,-31.6683,18.5012,19.36,19.36,0,61,3.73,1614968176,Voni's Cottage,\n<dl>\n<dt>Name</dt><dd>Voni's Cottage</dd>\n...
17,Verāval,IN,20.9000,70.3667,25.02,25.02,0,66,3.34,1614968177,HOTEL PLATINUM,\n<dl>\n<dt>Name</dt><dd>HOTEL PLATINUM</dd>\n...
18,Rāzole,IN,16.4833,81.8333,20.75,20.75,0,83,0.57,1614968186,Dindi By The Godavari,\n<dl>\n<dt>Name</dt><dd>Dindi By The Godavari...
19,Port Blair,IN,11.6667,92.7500,27.08,27.08,0,82,4.04,1614968114,Hotel Reef Atlantis,\n<dl>\n<dt>Name</dt><dd>Hotel Reef Atlantis</...
20,Pīpri,IN,19.8000,75.5333,23.00,23.00,0,40,1.03,1614968201,Hotel Siddheshwar,\n<dl>\n<dt>Name</dt><dd>Hotel Siddheshwar</dd...
21,Lüderitz,NaN,-26.6481,15.1594,22.32,22.32,0,48,6.81,1614968218,LÜDERITZ NEST HOTEL,\n<dl>\n<dt>Name</dt><dd>LÜDERITZ NEST HOTEL</...
22,Rewāri,IN,28.1833,76.6167,20.00,20.00,0,60,3.09,1614968220,Hotel Deep Palace,\n<dl>\n<dt>Name</dt><dd>Hotel Deep Palace</dd...
23,Coyhaique,CL,-45.5752,-72.0662,27.00,27.00,0,17,2.06,1614968222,Hotel Dreams de la Patagonia,\n<dl>\n<dt>Name</dt><dd>Hotel Dreams de la Pa...
24,Salalah,OM,17.0151,54.0924,26.00,26.00,0,57,1.54,1614968227,Salalah Gardens Hotel,\n<dl>\n<dt>Name</dt><dd>Salalah Gardens Hotel...
25,Sinazongwe,ZM,-17.2614,27.4618,25.40,25.40,0,60,1.60,1614968235,Lakeview Lodge,\n<dl>\n<dt>Name</dt><dd>Lakeview Lodge</dd>\n...
26,Sawākin,SD,19.1059,37.3321,22.81,22.81,0,62,5.57,1614968279,Arab Plaza Hotel عرب بلازا هوتيل,\n<dl>\n<dt>Name</dt><dd>Arab Plaza Hotel عرب ...
27,Pisco,PE,-13.7000,-76.2167,26.37,27.00,0,74,4.63,1614968283,Hotel Presidente,\n<dl>\n<dt>Name</dt><dd>Hotel Presidente</dd>...
28,Ritchie,ZA,-29.0380,24.6028,23.00,23.00,0,28,3.60,1614968284,The Cygnature Boutique Hotel,\n<dl>\n<dt>Name</dt><dd>The Cygnature Boutiqu...
29,Dalbandin,PK,28.8947,64.4101,22.30,22.30,0,21,1.40,1614968294,Al-Dawood Hotel & Restaurant,\n<dl>\n<dt>Name</dt><dd>Al-Dawood Hotel & Res...
30,Narasannapeta,IN,18.4167,84.0500,22.84,22.84,0,78,2.86,1614968303,SPR Grand Hotel,\n<dl>\n<dt>Name</dt><dd>SPR Grand Hotel</dd>\...
31,Gariāband,IN,20.6350,82.0614,24.00,24.00,0,35,2.57,1614968325,HOTEL CITY REGENCY,\n<dl>\n<dt>Name</dt><dd>HOTEL CITY REGENCY</d...

In [75]:
#locations = hd[["lat", "lon"]].astype(float)

rating = hd["humidity"]

 # Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, dissipating=False, max_intensity=100, point_radius=4)
markers = gmaps.marker_layer(locations)
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
    
)

fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig.add_layer(heat_layer)   
fig
#Perfect Vacation Destination Map for those looking for light wind, cloudless skies, and warm weather.

Figure(layout=FigureLayout(height='420px'))

#satellite